<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>IndependentTablespace.Samples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IndependentTablespace.Samples.Domain\IndependentTablespace.Samples.Domain.csproj" />
    <ProjectReference Include="..\IndependentTablespace.Samples.TestBase\IndependentTablespace.Samples.TestBase.csproj" />
  </ItemGroup>

</Project>
