<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>IndependentTablespace.Samples</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Code\Volo.Abp.Tenant.IndependentTablespace\Volo.Abp.Tenant.IndependentTablespace.csproj" />
		<ProjectReference Include="..\IndependentTablespace.Samples.Domain\IndependentTablespace.Samples.Domain.csproj" />
		<ProjectReference Include="..\IndependentTablespace.Samples.Application.Contracts\IndependentTablespace.Samples.Application.Contracts.csproj" />
		<ProjectReference Include="..\IndependentTablespace.Samples.EntityFrameworkCore\IndependentTablespace.Samples.EntityFrameworkCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.45.2" />
		<PackageReference Include="Volo.Abp.Account.Application" Version="8.3.0" />
		<PackageReference Include="Volo.Abp.Identity.Application" Version="8.3.0" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="8.3.0" />
		<PackageReference Include="Volo.Abp.TenantManagement.Application" Version="8.3.0" />
		<PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="8.3.0" />
		<PackageReference Include="Volo.Abp.SettingManagement.Application" Version="8.3.0" />
	</ItemGroup>

</Project>
